apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: default
spec:
  ports:
  - name: http
    targetPort: {{ .Values.port }}
    port: {{ .Values.port }}
  selector:
    app: {{ .Values.name }}
